version: '2'

networks:
  app-network:
    driver: bridge

services:
  redis:
    image: 'redis'
    container_name: 'redis-app'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network
  myapplication:
    image: 'nodejs-redis'
    ports:
      - "9000:9000"
    links:
      - redis
    expose:
      - "6379"
    networks:
      - app-network